### ISSUE TITLE
MetaMask txn error when selling certain cards

### ISSUE THREAD

**Issue by flfk** [CryptoAgainstHumanity/crypto-against-humanity#22]
Error only occurs on some cards (e.g. "$300 eth" card had error, "Pen15 coin" did not).
<img width="363" alt="screen shot 2018-06-11 at 4 53 35 pm" src="https://user-images.githubusercontent.com/24465371/41254113-d3120156-6d98-11e8-8301-637bca5e8fa1.png">

**Comment by Kyrrui** [comment]
Fixed with caching update.
