### ISSUE TITLE
Bug returns error, can't read property 'getBlockNumber'

### ISSUE THREAD

**Issue by sakibarifin** [CryptoAgainstHumanity/crypto-against-humanity#36]
![image](https://user-images.githubusercontent.com/33556544/41933257-29ee0d5e-79a5-11e8-8389-ad31c042969f.png)

The website is not usable because it shows nothing but error screen.

**Comment by Kyrrui** [comment]
@sakibarifin Ahh thanks for noticing this. This is from the most recent merge between my changes to non-metamask users and @flfk UI changes. I'll be sure to fix this. If you do want to view the site before I fix this, just install metamask :)

**Comment by Kyrrui** [comment]
Fixed @ commit https://github.com/CryptoAgainstHumanity/crypto-against-humanity/commit/8e8000e1f14f8b3b1f79c8b8416b3a53d237d55c
